version: "3"

services:
  xuexin-report:
    build:
      context: .
      dockerfile: Dockerfile
    image: xuexin-report:latest
    container_name: xuexin-report
    ports:
      - "8080:80"
    restart: unless-stopped
