server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    # 库文件缓存
    location /libs/ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
}
